### ISSUE TITLE
Missing LICENSE file?

### ISSUE THREAD

**Issue by briansturgill** [pchalamet/NPolyBool#3]
I am assuming you meant it to be MIT licensed?
You could grab the one from polybool.net and change it to your copyright...
https://github.com/idormenco/PolyBool.Net/blob/master/LICENSE
I am using it in a MIT license C# CAD package and would feel better if I knew for sure what your intentions were.
I have it online but am scaring people away at the moment. Not quite yet ready for general usage yet, though getting very close.
https://github.com/briansturgill/CSharpCAD
Thanks!
Brian

**Comment by pchalamet** [comment]
Hello Brian,

Glad it's useful but... It's not because there is no license, there should be no authorization and proper credits anyway.
**General rule of thumb for OSS projects: do not steal code and take credit for that.** 

I'm sure you do not intend this as you are notifying me but I invite you to:
* add a header on copied source files with proper credit and repository link
* add source code has been copied from this repository in the README.md

As long as you credit accordingly, it's ok for me.

NOTE: you could also have used the nuget package and send PR as required.

Thanks!
- Pierre

**Comment by briansturgill** [comment]
@pchalamet I, of course, fully intend to credit you.
I had been using polybool.net, but liked aspects of your code more.
The problem here is that copyright law (in absence of a LICENSE) defaults to others having no rights at all.
People that want to use this inside corporations would be very nervous about there not being a license.
So please, if  you could, add a LICENSE, otherwise I'll need to got back to polybool.net.
Thanks!
Brian

**Comment by pchalamet** [comment]
Intent was to push this code on Github to be used by anyone as original code helped me years ago. So your issue is fair but MIT is not - even if I have bunch of personal repositories licensed with MIT.

Anyway, as original license is MIT and this work is mostly derivative, it's fair to be MIT in turn. I'll push the license.

**Comment by briansturgill** [comment]
Thank you! Thank you! Thank You! One more thing of the list of things to do before release!
